name: MacOS

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            container: '{"image": "ghcr.io/homebrew/ubuntu22.04:master"}'
          - os: ubuntu-22.04-arm
            container: '{"image": "ghcr.io/homebrew/ubuntu22.04:master"}'
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container && fromJSON(matrix.container) || '' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install ROOT
        run: brew install root

      - name: configure
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -j

#      - name: test Currently no tests are implemented
#        run: |
#          cd build
#          ctest --build-config Debug