name: UpdateHomebrew

on:
  push:
    tags:
      - 'v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          homebrew-tap: 'vetlewi/homebrew-formula'
          formula-name: 'xia2tree'
          formula-path: 'Formula/xia2tree.rb'
          create-pullrequest: true
        env:
          # the personal access token should have "repo" & "workflow" scopes
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
